#!/bin/bash
#SBATCH -J Lei
#SBATCH --mem 10G
#SBATCH --ntasks 1
#SBATCH --qos castles
#SBATCH -t 00:30:00

module purge; module load bluebear
module load BCFtools/1.10.2-GCC-9.3.0
module load GCC/9.3.0

#download Dsuite
$ git clone https://github.com/millanek/Dsuite.git
$ cd Dsuite
$ make

#extract each chromosome
for i in {1..22};do bcftools view himalaya-samtools-feb21.vcf.gz  -r $i -O z -o chr$i.vcf.gz;done

#Dtrios
for i in {1..22};do ./Dsuite/Build/Dsuite Dtrios chr$i.vcf.gz Sample_POPs_IDs.txt -o chr$i;done
./Dsuite/Build/Dsuite Dtrios chrX.vcf.gz Sample_POPs_IDs.txt -o chrX
./Dsuite/Build/Dsuite Dtrios chrY.vcf.gz Sample_POPs_IDs.txt -o chrY

#Dinvestigate
./Dsuite/Build/Dsuite Dinvestigate himalaya-samtools-feb21.vcf.gz sets_Asian_Dinvestigate.txt test_trios_Asian.txt

 